# Generated by Django 5.1.7 on 2025-04-21 12:29
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="variant",
            name="description",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
