# Generated by Django 5.1.7 on 2025-03-16 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='name',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='task',
            name='skills',
            field=models.ManyToManyField(default=None, related_name='tasks_skills', to='skills.skill'),
        ),
    ]
