# Generated by Django 5.1.7 on 2025-04-21 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0002_variant_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='description',
        ),
        migrations.AddField(
            model_name='variant',
            name='kb_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='sm_description',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
