# Generated by Django 5.1.7 on 2025-03-29 20:02
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0002_variant_name_alter_task_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="taskuser",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
    ]
