# Generated by Django 5.1.7 on 2025-04-23 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0003_remove_variant_description_variant_kb_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKillConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('skill_from', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skill_from', to='skills.skill')),
                ('skill_to', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_to', to='skills.skill')),
            ],
        ),
    ]
