# Generated by Django 5.1.7 on 2025-04-24 00:02
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0004_skillconnection"),
    ]

    operations = [
        migrations.AlterField(
            model_name="skillconnection",
            name="skill_from",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="outputs",
                to="skills.skill",
            ),
        ),
        migrations.AlterField(
            model_name="skillconnection",
            name="skill_to",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="inputs",
                to="skills.skill",
            ),
        ),
    ]
