# Generated by Django 5.2 on 2025-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0004_alter_user_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
