# Generated by Django 5.1.7 on 2025-04-24 09:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_alter_skillconnection_skill_from_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='task',
        ),
        migrations.AddField(
            model_name='task',
            name='variant',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.variant'),
        ),
    ]
