# Generated by Django 5.2 on 2025-04-12 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0005_skill_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='userskill',
            name='mark',
            field=models.FloatField(default=100),
        ),
    ]
