# Generated by Django 5.1.7 on 2025-04-28 15:35
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("skills", "0006_remove_variant_task_task_variant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="variant",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="task",
                to="skills.variant",
            ),
        ),
    ]
