# Generated by Django 5.1.4 on 2025-01-20 20:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ATskills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fine', models.IntegerField(blank=True, null=True)),
                ('codificator1', models.IntegerField(blank=True, choices=[(1, 'Лексическая'), (2, 'Синтаксическая'), (3, 'Логическая')], null=True)),
                ('root_context', models.IntegerField(blank=True, choices=[(1, 'Тип'), (2, 'Объект'), (3, 'Событие'), (4, 'Интервалл'), (5, 'Правило'), (6, 'Тип ресурса'), (7, 'Ресурс'), (8, 'Образец операции'), (9, 'Операции'), (10, 'Функция')], null=True)),
                ('skills', models.ManyToManyField(blank=True, to='ATskills.skill')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ATskills.task')),
            ],
        ),
    ]
