# Generated by Django 5.1.7 on 2025-04-13 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mistake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mistake_type', models.IntegerField(choices=[(1, ' '), (2, ' '), (3, ' ')])),
                ('fine', models.FloatField(blank=True, null=True)),
                ('tip', models.TextField(blank=True, null=True)),
                ('is_tip_shown', models.BooleanField(default=False)),
                ('skills', models.ManyToManyField(blank=True, to='skills.skill')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='skills.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skills.user')),
            ],
        ),
    ]
