# Generated by Django 5.1.7 on 2025-04-23 10:30
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("mistakes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MistakeConnection",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("weight", models.FloatField()),
                (
                    "mistake_from",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="mistake_from", to="mistakes.mistake"
                    ),
                ),
                (
                    "mistake_to",
                    models.ForeignKey(
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mistake_to",
                        to="mistakes.mistake",
                    ),
                ),
            ],
        ),
    ]
