# Generated by Django 5.2 on 2025-04-12 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='mistake_type',
            field=models.IntegerField(choices=[(1, ' '), (2, ' '), (3, ' ')]),
        ),
    ]
