# Generated by Django 5.1.7 on 2025-04-23 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0002_mistakeconnection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MistakeConnection',
        ),
    ]
