# Generated by Django 5.2 on 2025-04-12 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mistakes', '0003_mistake_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mistake',
            name='fine',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
