# Generated by Django 5.1.4 on 2024-12-23 10:22
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "operation_type",
                    models.CharField(
                        choices=[
                            ("CREATE", "Create"),
                            ("UPDATE", "Update"),
                            ("DELETE", "Delete"),
                            ("GET", "Get"),
                            ("TRANSLATE", "Translate"),
                            ("IMPORT", "Import"),
                            ("EXPORT", "Export"),
                            ("COMPUTE", "Compute"),
                        ],
                        default="GET",
                        max_length=20,
                    ),
                ),
                (
                    "operand",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NIL", "Nil"),
                            ("MODEL", "Model"),
                            ("RESOURCE_TYPE", "Resource Type"),
                            ("RESOURCE", "Resource"),
                            ("FUNCTION", "Function"),
                            ("TEMPLATE", "Template"),
                            ("TEMPLATE_USAGE", "Template Usage"),
                        ],
                        default="NIL",
                        max_length=50,
                    ),
                ),
                ("params", models.JSONField()),
                (
                    "status",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("ERROR", "Error")], default="SUCCESS", max_length=10
                    ),
                ),
                ("error_code", models.IntegerField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("is_scenario", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("scenario_name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("task_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("event_params", models.JSONField(blank=True, null=True)),
                ("on_success", models.IntegerField()),
                ("on_failure", models.IntegerField()),
                ("skills", models.ManyToManyField(related_name="tasks", to="ATskills.skill")),
            ],
        ),
        migrations.CreateModel(
            name="ScenarioPart",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("scenario_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[("TODO", "To Do"), ("DONE", "Done"), ("IN_PROGRESS", "In Progress")],
                        default="TODO",
                        max_length=20,
                    ),
                ),
                (
                    "parent_tasks",
                    models.ManyToManyField(blank=True, related_name="child_tasks", to="ATskills.scenariopart"),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="scenario_parts", to="ATskills.task"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("message", models.TextField()),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reactions", to="ATskills.task"
                    ),
                ),
            ],
        ),
    ]
